*                soft    nofile          ${NOFILE_SOFT}
*                hard    nofile          ${NOFILE_HARD}
*                soft    nproc           ${NPROC_SOFT}
*                hard    nproc           ${NPROC_HARD}
*                soft    core            0
*                hard    core            0
*                soft    memlock         65536
*                hard    memlock         65536
root             soft    nofile          ${NOFILE_SOFT}
root             hard    nofile          ${NOFILE_HARD}
root             soft    nproc           unlimited
root             hard    nproc           unlimited
www-data         soft    nofile          ${NOFILE_HARD}
www-data         hard    nofile          ${NOFILE_HARD}
haproxy          soft    nofile          ${NOFILE_HARD}
haproxy          hard    nofile          ${NOFILE_HARD}
