auth,authpriv.*                 /var/log/auth.log
*.*;auth,authpriv.none          -/var/log/syslog
cron.*                          /var/log/cron.log
kern.*                          -/var/log/kern.log
local0.*                        -/var/log/haproxy.log
& stop
