server {
    listen ${BARAT_HTTP_PORT};
    listen [::]:${BARAT_HTTP_PORT};
    server_name ${HOST_BARAT};

    access_log /var/log/nginx/barat-redirect.log;

    location / {
        return 301 https://${HOST_BARAT}:${BARAT_HTTPS_PORT}$request_uri;
    }
}

server {
    listen ${BARAT_HTTPS_PORT} ssl${LISTEN_SSL_SUFFIX};
    listen [::]:${BARAT_HTTPS_PORT} ssl${LISTEN_SSL_SUFFIX};
${HTTP2_DIRECTIVE}
    server_name ${HOST_BARAT};
    root ${BARAT_DOCROOT};
    index index.html;

    ssl_certificate     ${BARAT_CRT};
    ssl_certificate_key ${BARAT_KEY};
    ssl_dhparam         /etc/nginx/dhparam.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_session_cache shared:SSL_BARAT:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    add_header Strict-Transport-Security "max-age=${HSTS_MAX_AGE}" always;
    add_header X-Owner-By "${PESERTA_NAMA}" always;
    add_header X-Served-By "nginx" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "no-referrer" always;

    access_log /var/log/nginx/barat-access.log;
    error_log  /var/log/nginx/barat-error.log;

    location ~ /\. {
        deny all;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
