server {
    listen ${TIMUR_PORT};
    listen [::]:${TIMUR_PORT};

    server_name ${HOST_TIMUR} ${HOST_WWW};
    root ${TIMUR_DOCROOT};
    index index.html;

    add_header X-Owner-By "${PESERTA_NAMA}" always;
    add_header X-Served-By "${TIMUR_SERVED_BY}" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "no-referrer" always;

    access_log /var/log/nginx/timur-access.log;
    error_log  /var/log/nginx/timur-error.log;

    location ~ /\. {
        deny all;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
