ServerName ${HOST_UTARA}
ServerTokens Prod
ServerSignature Off
TraceEnable Off

RemoteIPHeader X-Forwarded-For
RemoteIPInternalProxy 127.0.0.1
RemoteIPInternalProxy ::1

LogFormat "%a %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" sevima
