[Service]
LimitNOFILE=${NOFILE_HARD}
LimitNPROC=${NPROC_HARD}
NoNewPrivileges=yes
PrivateTmp=yes
ProtectHome=read-only
ProtectSystem=full
ProtectKernelTunables=yes
ProtectControlGroups=yes
RestrictSUIDSGID=yes
