#!/usr/bin/env bash

PESERTA_ID="99"
PESERTA_NAMA="Umar Sabirin"

PORT_MODE="gabung"

DOMAIN_BASE="sevima.site"
HOST_WWW="www.${DOMAIN_BASE}"
HOST_UTARA="utara.${DOMAIN_BASE}"
HOST_TIMUR="timur.${DOMAIN_BASE}"
HOST_BARAT="barat.${DOMAIN_BASE}"

SSH_PORT=2025
SSH_DROPIN="/etc/ssh/sshd_config.d/01-sevima.conf"
SSH_REQUIRE_BOTH_FACTORS="no"

FAIL2BAN_ENABLE="yes"
FAIL2BAN_MAXRETRY=5
FAIL2BAN_FINDTIME="10m"
FAIL2BAN_BANTIME="1h"
FAIL2BAN_IGNOREIP=""

ENABLE_UFW="no"

USER_PREFIX="sevima-adm"
USER_COUNT=1300
USER_PASSWORD_PREFIX="w3bsite#"
USER_SUDO_GROUP="sudo"
USER_KEY_DIR="/root/sevima-keys"

SUDO_IO_RETENTION_DAYS=14

CA_DIR="/root/ca"
CA_COUNTRY="ID"
CA_ORG="PT. Sentra Vidya Utama"
CA_CN="SEVIMA CA"
CA_KEY_BITS=4096
CA_DAYS=3650
CERT_DAYS=825
CA_TRUST_NAME="sevima-ca"

BARAT_HTTPS_PORT=4435
BARAT_HTTP_PORT=8080

HAPROXY_HTTP_PORT=80
HAPROXY_HTTPS_PORT=443
HAPROXY_CERT_DIR="/etc/haproxy/certs"

HSTS_MAX_AGE=300

TIMUR_SERVED_BY="nginx"

WEBROOT_BASE="/var/www"
